
#' An internal customized ggplot2 theme for all the plots
#' generated by ViSAGE
#'
#' @noRd
boris_theme <- function(){
  ggplot2::theme_bw() +
    ggplot2::theme(
      axis.text       = ggplot2::element_text(color = "black", size = 16),
      axis.title      = ggplot2::element_text(colour = "black", face = "bold", size = 16),
      legend.text     = ggplot2::element_text(colour = "black", size = 16),
      legend.position = "none",
      legend.title    = ggplot2::element_blank(),
      panel.grid      = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(fill = "white", colour = NA),
      panel.border    = ggplot2::element_rect(colour = "black"),
      text            = ggplot2::element_text(colour = "black", size = 16)
    )
}


####A function to create the founders +++++++++++++++++++++++++ ####
#' Create a founder population using AlphaSimR.
#' @description
#' This function simulates a founder population with specified parameters such
#' as the number of founders, number of chromosomes, and number of segregating sites.
#'
#' @param nfounders an integer representing the number of founders to be simulated.
#' @param nChrom an integer representing the number of chromosomes in the simulated genome.
#' @param nSites an integer representing the total number of segregating sites across the genome.
#' The function will distribute these sites evenly across the specified number of chromosomes.
#'
#' @returns An AlphaSimR founder population object.
#' @noRd
create_founders <- function(nfounders = 100, nChrom = 10, nSites = 200){
  founders <- AlphaSimR::quickHaplo(nInd = nfounders, nChr = nChrom,
                                 segSites = ceiling(2*nSites/nChrom),
                                 inbred = FALSE)
  return(founders)
}


#' Convert to HapMap format
#' @description
#' The function below was written by Alex Lipka on February 20, 2024. It is designed
## to take SNPs simulated from AlphaSimR and create a
# "hapmap-formatted" data that can be read into simplePHENOTYPES
#'
#' @param these.SNPs a matrix of snp maker genotypes
#' @param this.physical.map a data frame containing the physical map information for snp markers.
#'
#' @returns A data frame in HapMap format that can be used as input for simplePHENOTYPES.
#' @noRd
get.me.my.SNPs.in.hapmap.format <- function(these.SNPs = NA,
                                            this.physical.map = NA){
  # Subtract the numeric genotypes so that they range from -1,0,1
  these.SNPs.minus.one <- these.SNPs-1

  #Arrange the SNPs and genetic map  so that they are in a HapMap-like format
  # for simplePHENOTYPES
  hapmap.file.of.these.SNPs <- data.frame(
    snp = colnames(these.SNPs.minus.one),
    allele = rep("A/G", ncol(these.SNPs.minus.one)),
    chr = this.physical.map$chr,
    pos = this.physical.map$pos,
    cm = rep(NA, ncol(these.SNPs.minus.one)),
    t(these.SNPs.minus.one)
  )

  return(hapmap.file.of.these.SNPs)
} #end get.me.my.SNPs.in.hapmap.format

#' Compute MAF and sort SNPs in ascending order of MAF values
#'
#' @param geno_dt a data frame of snp markers scores from AlphasimR suing pullSegGeno
#' @param qtns a vector of snp names selected to be qtns
#'
#' @returns a vector of sorted snps names based on MAF
#' @noRd
#'
compute_sort_MAF <- function(geno_dt, qtns) {

  # geno_dt <- AlphaSimR::pullQtlGeno(pop, trait = 1, simParam = SP_object)
  geno_df <- data.frame(ID = paste0("ID",1:nrow(geno_dt)), geno_dt)
  qtns <- paste0("X", qtns)
  geno_df <- geno_df |> dplyr::select_at(c("ID", qtns))

  # Input validation

  if (!"ID" %in% colnames(geno_df)) {
    stop("The firtst column of geno_df must be the 'ID' column.")
  }

  # Quick stats

  markers <- colnames(geno_df)[-1]
  nloci <- length(markers)
  nindiv <- nrow(geno_df)

  # Convert to long format

  long_df <- tidyr::pivot_longer(
    data = geno_df,
    cols = dplyr::all_of(markers),
    names_to = "SNP",
    values_to = "Dosage"
  )

  # Genotype means and counts
  genotype_stats <- dplyr::group_by(long_df, SNP, Dosage) |>
    dplyr::summarise(n = dplyr::n(),
                     .groups = "drop") |>
    tidyr::pivot_wider(names_from = Dosage,
                       values_from = n,
                       names_prefix = "freq_")

  # Allele frequency

  # Ensure required columns exist
  for (col in c("freq_0", "freq_1", "freq_2")) {
    if (!col %in% names(genotype_stats)) {
      genotype_stats[[col]] <- 0
    }
  }

  allele_freq <- genotype_stats |>
    dplyr::mutate(
      p = (2 * freq_0 + freq_1) / (2 * nindiv),
      q = 1 - p,
      maf = pmin(p,q, na.rm = T)) |>
    dplyr::arrange(maf)

  ## Ordered markers
  ordered_snps <- sub("X","", allele_freq$SNP)
  # out_list <- list(allele_freq = allele_freq,
  # ordered_snps = ordered_snps)

  return(ordered_snps)

}

#' Random selection of snps from a data frame to be used as QTNs
#'
#' @param hapmap_obj a data frame of snp markers scores in hapmap format
#' @param a_qtns an integer representing the number of additive qtns
#' @param d_qtns an integer representing the number of dominance qtns
#' @param e_qtns an integer representing the number of pairwise epistatic qtns
#' @param seed_num an integer representing the seed number
#'
#' @returns a list with all slected snps as qtns
#' @noRd
#'
select_qtns <- function(hapmap_obj, a_qtns, d_qtns, e_qtns, seed_num){
  if(identical(c(a_qtns, d_qtns, e_qtns), rep(0,3))){
    stop("")
  }else{
    set.seed(seed = seed_num)
    a_list <- sample(hapmap_obj$snp, a_qtns)
    d_list <- sample(setdiff(hapmap_obj$snp, a_list), d_qtns)
    e_list <- sample(setdiff(hapmap_obj$snp, c(a_list, d_list)), 2*e_qtns)

    QTN_list <- list()
    QTN_list$add[[1]] <- a_list
    QTN_list$dom[[1]] <- d_list
    QTN_list$epi[[1]] <- e_list
    return(QTN_list)
  }

}

### An updated function to create the base population (AlphaSimR)
#' Create a base population using AlphaSimR.
#' @description
#' This function simulates a base population based on a founder population and
#' specified parameters by the user.
#'
#' @param founders an AlphaSimR founder population object.
#' @param nQTN an integer representing the number of quantitative trait nucleotides (QTNs).
#' @param tMean a integer representing the population mean value for the trait.
#' @param tVA a numeric value representing the additive genetic variance for the trait.
#' @param tVD a numeric value representing the dominance genetic variance for the trait.
#' @param tVE a numeric value representing the epistatic genetic variance for the trait.
#' @param tdomDeg a numeric value representing the mean dominance degree for the trait.
#' @param tVDomDeg a numeric value representing the variance of dominance degree for the trait.
#' @param tHet a numeric value representing the broad-senseheritability of the trait.
#'
#' @returns A list containing the genetic architecture 'arch' of the trait and the simulated base population object.
#' @noRd
create_base_pop <- function(founders, sp_object, nQTN = NULL, tMean = NULL,
                            tVA=25, tVD=0, tVE=0, tdomDeg= 0, tVDomDeg = 0, tHet=NULL){
  nChrom <- founders@nChr
  SP <- sp_object
  SP$resetPed()

  ##If trait is pure Additive
  if(tVD == 0 & tVE == 0){
    SP$addTraitA(nQtlPerChr = ceiling(nQTN[1]/nChrom), name = "Trait1", mean = tMean[1], var = tVA[1])

    ##If trait is Additive + Dominance
  }else if(tVD != 0 & tVE == 0){
    SP$addTraitAD(nQtlPerChr = ceiling(nQTN[1]/nChrom), name = "Trait1", mean = tMean[1], var = tVA[1] + tVD[1],
                  meanDD = tdomDeg[1], varDD = tVDomDeg[1])

    ##If trait is Additive + Epistasis
  }else if(tVD == 0 & tVE != 0){
    SP$addTraitAE(nQtl = ceiling(nQTN[1]/nChrom), mean = tMean[1], var = tVA[1]+tVE[1],
                  name = "Trait1", relAA = tVE[1]/tVA[1])
    #relAA = traitVE/traitVA

    ##If trait is Additive + Dominance + Epistasis
  }else if(tVD != 0 & tVE != 0){
    SP$addTraitADE(nQtl = ceiling(nQTN[1]/nChrom), mean = tMean[1], var = tVA[1]+tVE[1]+tVD[1],
                   name = "Trait1", relAA = tVE[1]/tVA[1],
                   meanDD = tdomDeg[1], varDD = tVDomDeg[1])
  }

  ## Create base population and set heritablity to get pheno
  pop <- AlphaSimR::newPop(founders, simParam = SP)
  pop <- AlphaSimR::setPheno(pop, H2 = tHet, simParam = SP)
  out <- list(arch = " ", pop = pop, QTN_list = NULL)
  return(out)
}


#### This function creates an SP object available within the simulation env.
local_sp <- function(f_pop){
  SP <- AlphaSimR::SimParam$new(f_pop)
  return(SP)
}

### An updated function to create the base population (simplePHENOTYPES)
#' Create a base population using AlphaSimR and simplePHENOTYPES.
#'
#' @param founders an AlphaSimR founder population object.
#' @param tMean a numeric value representing the population mean value for the trait.
#' @param a_QTNs an integer representing the number of additive QTNs for the trait.
#' @param d_QTNs an integer representing the number of dominance QTNs for the trait.
#' @param e_QTNs an integer representing the number of epistatic QTNs for the trait.
#' @param big_a_eff a numeric value representing the effect size of the major additive QTNs for the trait.
#' @param a_eff a numeric value representing the effect size of the minor additive QTNs for the trait.
#' @param d_eff a numeric value representing the effect size of the dominance QTNs for the trait.
#' @param e_eff a numeric value representing the effect size of the epistatic QTNs for the trait.
#' @param tHet a numeric value representing the broad-sense heritability of the trait.
#' @param sp_object a simulation parameter container from AlphaSimR
#' @param sort_maf a string to determine whether to implement negative correlation between MAF and additive effect size
#'
#' @returns A list containing the genetic architecture 'arch' of the trait and the simulated base population object.
#' @noRd
create_base_pop_sp <- function(founders, sp_object, tMean = NULL,
                            a_QTNs = 0, d_QTNs = 0, e_QTNs = 0,
                            big_a_eff = 0, a_eff = 0, d_eff = 0, e_eff = 0, tHet=NULL, sort_maf = "No"){

  ## Required conditions for the simulations
  if(identical(c(a_QTNs,d_QTNs, e_QTNs), rep(0,3))){
    stop("At least one of the QTN types must be provided.")
  }
  if(identical(c(big_a_eff, a_eff, d_eff, e_eff), rep(0,4))){
    stop("At least one of the effect types must be provided.")
  }

  nChrom <- founders@nChr
  nQTN <- sum(a_QTNs, d_QTNs, 2*e_QTNs, na.rm = T)

  SP <- sp_object
  SP$resetPed()
  ##This is just a dummy trait
  SP$addTraitA(nQtlPerChr = ceiling(nQTN[1]/nChrom), name = "Trait1", mean = 0, var = 64)



  # ## Create base population. Note, pop cannot be created unless trait is added to SP.
  pop <- AlphaSimR::newPop(founders, simParam = SP)

  ## Set the phenotype for the base population
  ### Pulling out the genotypic/genomic data. This Does not work unless you have added a trait.
  bp_qtl_map <- AlphaSimR::getQtlMap(trait = 1, simParam = SP)
  bp_qtls <- AlphaSimR::pullQtlGeno(pop, trait = 1, simParam = SP)

  #The function by Alex transforms the snp data into hapmap format needed for simplePHENOTYPES
  bp_qtls_hapmap <- get.me.my.SNPs.in.hapmap.format(these.SNPs = bp_qtls, this.physical.map = bp_qtl_map)

  ### a nested function to manually select QTNs
  select_qtns <- function(hapmap_obj, a_qtns, d_qtns, e_qtns, seed_num){
    if(identical(c(a_qtns, d_qtns, e_qtns), rep(0,3))){
      stop("")
    }else{
      set.seed(seed = seed_num)
      a_list <- sample(hapmap_obj$snp, a_qtns)
      d_list <- sample(setdiff(hapmap_obj$snp, a_list), d_qtns)
      e_list <- sample(setdiff(hapmap_obj$snp, c(a_list, d_list)), 2*e_qtns)

      QTN_list <- list()
      QTN_list$add[[1]] <- a_list
      QTN_list$dom[[1]] <- d_list
      QTN_list$epi[[1]] <- e_list
      return(QTN_list)
    }

  }

  QTN_list <- select_qtns(hapmap_obj = bp_qtls_hapmap, a_qtns = a_QTNs,
                          d_qtns = d_QTNs, e_qtns = e_QTNs, seed_num = 1989)

  ### a nested function to order QTNs
  compute_sort_MAF <- function(geno_dt, qtns) {

    # Add ID column (avoid full data.frame copy if possible)
    geno_df <- data.frame(ID = paste0("ID", seq_len(nrow(geno_dt))), geno_dt)

    # Fix marker names (prefix X if starting with number)
    qtns <- ifelse(grepl("^[0-9]", qtns), paste0("X", qtns), qtns)

    # Select only required columns
    geno_df <- dplyr::select(geno_df, "ID", dplyr::all_of(qtns))

    # Input validation
    if (!"ID" %in% colnames(geno_df)) {
      stop("The first column of geno_df must be 'ID'.")
    }

    # Extract genotype matrix (avoid repeated indexing)
    geno_mat <- as.matrix(geno_df[, -1, drop = FALSE])
    nindiv <- nrow(geno_mat)

    # Replace NA with 0 (or decide if you want NA-aware calculation)
    geno_mat[is.na(geno_mat)] <- 0

    # Compute allele frequency directly
    # p = frequency of allele coded as 0 (based on your formula)
    p <- colSums(2 * (geno_mat == 0) + 1 * (geno_mat == 1)) / (2 * nindiv)

    q <- 1 - p
    maf <- pmin(p, q)

    # Create result dataframe
    allele_freq <- data.frame(
      SNP = colnames(geno_mat),
      p = p,
      q = q,
      maf = maf
    )

    # Sort by MAF
    allele_freq <- dplyr::arrange(allele_freq, maf)

    # Remove "X" prefix if added earlier
    ordered_snps <- sub("^X", "", allele_freq$SNP)

    return(ordered_snps)
  } # End of function compute_sort_MAF

  if(sort_maf == "Yes"){
    snps <- QTN_list$add[[1]]
    ord_snps <- compute_sort_MAF(geno_dt = bp_qtls, qtns = snps)
    QTN_list$add[[1]] <- ord_snps
  }

  ## Determine the genetic architecture of the trait
  arch <- ""
  if (a_QTNs != 0 & !identical(c(a_eff, big_a_eff), rep(0,2))) arch <- paste0(arch, "A")
  if (d_QTNs != 0 & d_eff != 0) arch <- paste0(arch, "D")
  if (e_QTNs != 0 & e_eff != 0) arch <- paste0(arch, "E")


  a_QTNs    <- if (a_QTNs   == 0) NULL else a_QTNs
  big_a_eff <- if (big_a_eff == 0) NULL else big_a_eff
  a_eff     <- if (a_eff    == 0) NULL else a_eff

  d_QTNs    <- if (d_QTNs   == 0) NULL else d_QTNs
  d_eff     <- if (d_eff    == 0) NULL else d_eff

  e_QTNs    <- if (e_QTNs   == 0) NULL else e_QTNs
  e_eff     <- if (e_eff    == 0) NULL else e_eff

  # a_QTNs <<- a_QTNs; big_a_eff <<- big_a_eff; a_eff <<- a_eff;
  # d_QTNs <<- d_QTNs; d_eff <<- d_eff; e_QTNs <<- e_QTNs; e_eff <<- e_eff

  ### Use simplePHENOTYPES to create the Genetic values and phenotype values for the base population.
  pheno.value <- simplePHENOTYPES::create_phenotypes(geno_obj = bp_qtls_hapmap,
                                            ntraits = 2,
                                            h2 = c(tHet, 1),
                                            mean = rep(tMean,2),
                                            rep = 1,
                                            #Select QTNs manually
                                            QTN_list = QTN_list,
                                            #Additive
                                            add_QTN_num = a_QTNs,
                                            big_add_QTN_effect = rep(big_a_eff, 2),
                                            add_effect = list(a_eff, a_eff),
                                            #Dominance
                                            dom_QTN_num = d_QTNs,
                                            dom_effect = list(d_eff, d_eff),
                                            #Epistasis
                                            epi_QTN_num = e_QTNs,
                                            epi_effect = list(e_eff, e_eff),
                                            # sim_method = "geometric",
                                            #specify trait architecture
                                            model = arch,
                                            home_dir = tempdir(),
                                            to_r = TRUE,
                                            quiet = T,
                                            seed = sample(1:1000,1))

  ## Import the genetic and phenotypic values back into the population object

  # pop@gv <- as.matrix(gen.value[,2])
  pop@pheno <- as.matrix(pheno.value[,2])
  pop@gv <- as.matrix(pheno.value[,3])

  out <- list(arch = arch, pop = pop, QTN_list = QTN_list, hapmap = bp_qtls_hapmap)

  return(out)
}


#### A function to plot PCA biplot of snp data +++++++++++++++++++++++++ #######
plot_pca_biplot <- function(pop = NULL, geno = NULL){
  if(!is.null(pop)){
    geno_mat <- AlphaSimR::pullSegSiteGeno(pop)
  }else if(!is.null(geno)){
    geno_mat <- geno[,-1]
  }else{stop("You need to provide either a pop object or a marker data (geno).")}

  # Find monomorphic markers
  find_constant_cols <- function(df, values = c(0, 1, 2)) {
    names(df)[sapply(df, function(x) {
      ux <- unique(na.omit(x))
      length(ux) == 1 && ux %in% values
    })]
  }

  monomorphics <- find_constant_cols(df = as.data.frame(geno_mat))

  ## Exclude the monomorphics
  geno_mat <- geno_mat[,-which(colnames(geno_mat) %in% monomorphics)]

  ## Now run PCA analysis
  pca_res <- stats::prcomp(geno_mat, center = T, scale. = T)
  pca_var <- (summary(pca_res)$importance)[2,1:2]
  num_axis <- ifelse(length(pca_res$sdev) > 10, 10, length(pca_res$sdev))
  pca_var_df <- as.data.frame(t(100*(summary(pca_res)$importance)[2:3,1:num_axis])) |>
    dplyr::mutate(axes = 1:num_axis)
  colnames(pca_var_df) <- c("Prop_var", "Cum_var", "axes")
  pca_df <- as.data.frame(pca_res$x[,1:5])

  biplt <- ggplot2::ggplot(pca_df, ggplot2::aes(x = PC1, y = PC2)) +
    ggplot2::geom_point(alpha = 0.7, color = "darkblue") +
    ggplot2::labs(x = paste0("PC1 ", round(100*pca_var[1],2), "%"),
                  y = paste0("PC2 ", round(100*pca_var[2],2), "%")) +
    boris_theme()

  screeplt <- ggplot2::ggplot(data = pca_var_df, ggplot2::aes(x = axes)) +
    ggplot2::geom_point(ggplot2::aes(y = Prop_var, color = "Proportion"), size = 3) +
    ggplot2::geom_line(ggplot2::aes(y = Prop_var, color = "Proportion"), linewidth  = 1) +
    ggplot2::geom_point(ggplot2::aes(y = Cum_var, color = "Cumulative"), size = 3) +
    ggplot2::geom_line(ggplot2::aes(y = Cum_var, color = "Cumulative"), linewidth  = 1) +
    ggplot2::labs(x = "Axes", y = "% Variance") +
    ggplot2::scale_x_continuous(breaks = 1:num_axis, labels = paste0("PC", 1:num_axis)) +
    # ggplot2::scale_y_continuous(limits = c(0,100) ,breaks = seq(0,100,20)) +
    ggplot2::scale_color_manual(values = c("Proportion" = "darkblue", "Cumulative" = "darkred"))+
    boris_theme() + ggplot2::theme(legend.position = c(0.3, 0.8),
                                   axis.text.x = ggplot2::element_text(angle = 90, hjust = 1))

  out_list <- list(biplt = biplt, screeplt = screeplt)

  return(out_list)
}


import_population <- function(genotype, gene_map){
  if(!identical(colnames(gene_map),c("markerName","chromosome", "position"))){
    stop("gene_map should have snps in rows and the columns should be labeled: markerName, chromosome, and position in the order")
  }
  if(nrow(gene_map) != ncol(genotype)-1){
    stop("The number of marker in the gene_map and genotype files DO NOT MATCH")
  }
  genotype <- genotype |>
    tibble::column_to_rownames(var = names(genotype)[1]) |>
    as.matrix()
  pedig <- data.frame("id" = rownames(genotype),
                      "mother" = rep(0,nrow(genotype)),
                      "father" = rep(0, nrow(genotype)))

  if(max(gene_map$position, na.rm = T) > 1e6){
    gene_map$position <- cumsum(gene_map$position/1e8)
  }
  #geno should be a data frame with indiv as rows and snps as columns, and the first column is id, then markernames
  #gene_map should have snps in rows and the columns: markerName, chromosome, and position
  #ped should have individuals in rows and columns: id, mother, and father
  num_seg_sites <- ncol(genotype)
  num_founders <- nrow(genotype)
  num_chrom <- length(unique(gene_map$chromosome))

  #### create founder population
  founders <- AlphaSimR::importInbredGeno(geno = genotype, genMap = gene_map, ped = pedig)

  # out_list <- list(founders = founders, num_seg_sites = num_seg_sites,
  #                  num_founders = num_founders, num_chrom = num_chrom)
  return(founders)
}
